# Generated by Django 6.0.6 on 2026-09-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='evening_not_studied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='morning_not_studied',
            field=models.BooleanField(default=False),
        ),
    ]
